use xlqhgpsg_DB_RHH;
   CREATE TABLE PERSONA
  (
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(25)  NOT NULL,
	APELLIDOS VARCHAR(25)  NOT NULL,
	CI VARCHAR(25) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASS VARCHAR(25)  NOT NULL,
	DIRECCION VARCHAR(50)  NOT NULL,
    FOTO VARCHAR(45) NOT NULL,
	CANT_INTENTO TINYINT UNSIGNED NOT NULL,
    VISITAS INT UNSIGNED NOT NULL,
	ESTADO BOOLEAN NOT NULL,
	 
    PRIMARY KEY (ID)
    )ENGINE = InnoDB;

 

    CREATE TABLE PACIENTE
	(
    ID_PERSONA INT UNSIGNED NOT NULL,
    PRIMARY KEY (ID_PERSONA),
    ESTADO BOOL NOT NULL,
    FOREIGN KEY (ID_PERSONA)REFERENCES PERSONA(ID)
	on delete cascade
    on update cascade
    )ENGINE = InnoDB;
    
      CREATE TABLE DOCTOR
	(
    ESPECIALIDAD VARCHAR(50) NOT NULL,
    ID_PERSONA INT UNSIGNED NOT NULL,
    PRIMARY KEY (ID_PERSONA),
    ESTADO BOOL NOT NULL,
    FOREIGN KEY (ID_PERSONA)REFERENCES PERSONA(ID)
	on delete cascade
    on update cascade
    )ENGINE = InnoDB; 
    
       CREATE TABLE ENFERMERA
	(
 	ESPECIALIDAD VARCHAR(50)   NOT NULL,
    ID_PERSONA INT UNSIGNED NOT NULL,
    PRIMARY KEY (ID_PERSONA),
    ESTADO BOOL NOT NULL,
    FOREIGN KEY (ID_PERSONA)REFERENCES PERSONA(ID)
	on delete cascade
    on update cascade
    )ENGINE = InnoDB; 
    
	CREATE TABLE DIAGNOSTICOS
	(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	DESCRIPCION VARCHAR(50)  NOT NULL,
    ID_PACIENTE INT UNSIGNED NOT NULL,
    PRIMARY KEY (ID),
    ESTADO BOOL NOT NULL,
    FOREIGN KEY (ID_PACIENTE)REFERENCES PACIENTE(ID_PERSONA)
	on delete cascade
    on update cascade
    )ENGINE = InnoDB;
    
        CREATE TABLE CENTRODESALUD
	(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	NOMBRE VARCHAR(25)  NOT NULL,
	LUGAR VARCHAR(20)  NOT NULL,
    ESTADO BOOL NOT NULL,
    PRIMARY KEY (ID)
    )ENGINE = InnoDB;
    
    CREATE TABLE CONSULTORIO
(
	ID_DOCTOR INT unsigned NOT NULL,
    ID_CENTRODESLUD INT unsigned NOT NULL,
    PRIMARY KEY (ID_DOCTOR,ID_CENTRODESLUD),
    FOREIGN KEY (ID_DOCTOR)REFERENCES DOCTOR(ID_PERSONA),
    FOREIGN KEY (ID_CENTRODESLUD)REFERENCES CENTRODESALUD(ID)
)ENGINE = InnoDB;
 -- EDITAR:   
       CREATE TABLE CARGO
(
	ID_ENFERMERA INT unsigned NOT NULL,
    ID_CENTRODESLUD INT unsigned NOT NULL,
    PRIMARY KEY (ID_ENFERMERA,ID_CENTRODESLUD),
    FOREIGN KEY (ID_ENFERMERA)REFERENCES ENFERMERA(ID_PERSONA),
    FOREIGN KEY (ID_CENTRODESLUD)REFERENCES CENTRODESALUD(ID)
)ENGINE = InnoDB;